#pragma once

typedef enum {
    PIS_ERR_SUCCESS = 0,
    PIS_ERR_GENERIC,
    PIS_ERR_UNSUPPORTED_INSN,
    PIS_ERR_EARLY_EOF,
    PIS_ERR_NULL_ARG,
    PIS_ERR_TOO_MANY_INSNS,
    PIS_ERR_TOO_MANY_TMPS,
    PIS_ERR_ADDR_OVERFLOW,

    PIS_ERR_EMU_OUT_OF_STORAGE,
    PIS_ERR_EMU_READ_UNINIT,
    PIS_ERR_EMU_OPCODE_WRONG_OPERANDS_AMOUNT,
    PIS_ERR_EMU_OPERAND_SIZE_MISMATCH,
    PIS_ERR_EMU_COND_EXPR_WRONG_VALUE,

    PIS_ERR_X86_2_LEGACY_PREFIXES_OF_SAME_GROUP,
} err_t;
